# Generated by Django 4.0.4 on 2022-04-23 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(default='...', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('distance', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
            ],
            options={
                'db_table': 'market_data.market_data',
            },
        ),
    ]
