# Generated by Django 4.0.4 on 2022-04-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablecontent',
            table='market_data',
        ),
    ]
