# Generated by Django 4.0.4 on 2022-04-23 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecontent',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablecontent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tablecontent',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tablecontent',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tablecontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='tablecontent',
            table='market_data',
        ),
    ]
