# Generated by Django 4.0.3 on 2022-05-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_tablecontent_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablecontent',
            table='market_data.market_data',
        ),
    ]
