# Generated by Django 4.0.3 on 2022-05-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_tablecontent_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablecontent',
            table='publics.market_data',
        ),
    ]
